name: structured_async
description: Structured asynchronous programming in Dart.
version: 0.3.1
homepage: https://github.com/renatoathaydes/structured_async

environment:
  sdk: '>=2.19.0 <3.0.0'

dev_dependencies:
  dartle: ^0.22.2
  lints: ^1.0.0
  test: ^1.16.0
