name: structured_async
description: Structured asynchronous programming in Dart.
version: 0.0.0
homepage: https://github.com/renatoathaydes/structured_async

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
